import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-[url('/Northern_Lights_Revontulet_Wide.jpeg')]  bg-cover bg-center bg-no-repeat min-h-screen">
        <NavBar />
        <main>{children}</main>
  
      </body>
    </html>
  );
}
